# Generated by Django 6.0.2 on 2026-02-07 22:10

import uuid
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ingredient", "Ingredient"),
                            ("chemical", "Chemical"),
                            ("finished_good", "Finished Good"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        choices=[
                            ("malt", "Malt"),
                            ("hops", "Hops"),
                            ("yeast", "Yeast"),
                            ("adjunct", "Adjunct"),
                            ("cleaner", "Cleaner"),
                            ("sanitizer", "Sanitizer"),
                            ("water_treatment", "Water Treatment"),
                            ("keg", "Keg"),
                            ("can", "Can"),
                            ("bottle", "Bottle"),
                            ("case", "Case"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("lb", "lb"),
                            ("oz", "oz"),
                            ("g", "g"),
                            ("kg", "kg"),
                            ("gal", "gal"),
                            ("L", "L"),
                            ("mL", "mL"),
                            ("each", "each"),
                            ("pack", "pack"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
