# Generated by Django 6.0.2 on 2026-02-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("malt", "Malt"),
                    ("hops", "Hops"),
                    ("yeast", "Yeast"),
                    ("adjunct", "Adjunct"),
                    ("fruit_flavor", "Fruit/Flavor"),
                    ("cleaner", "Cleaner"),
                    ("sanitizer", "Sanitizer"),
                    ("water_treatment", "Water Treatment"),
                    ("keg", "Keg"),
                    ("can", "Can"),
                    ("bottle", "Bottle"),
                    ("case", "Case"),
                ],
                max_length=20,
            ),
        ),
    ]
