# Generated by Django 6.0.2 on 2026-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_seed_recipes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="earmarked_for",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="earmarked_for",
            field=models.ManyToManyField(
                blank=True, related_name="earmarked_items", to="inventory.recipe"
            ),
        ),
    ]
