# Generated by Django 6.0.2 on 2026-02-15 00:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_change_earmarked_to_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="abv",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Alcohol by volume percentage",
                max_digits=4,
                null=True,
                verbose_name="ABV %",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ibu",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="International Bitterness Units",
                null=True,
                verbose_name="IBU",
            ),
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("lb", "lb"),
                            ("oz", "oz"),
                            ("g", "g"),
                            ("kg", "kg"),
                            ("gal", "gal"),
                            ("L", "L"),
                            ("mL", "mL"),
                            ("each", "each"),
                            ("pack", "pack"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        limit_choices_to={"category": "ingredient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_usages",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="inventory.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["ingredient__subcategory", "ingredient__name"],
                "unique_together": {("recipe", "ingredient")},
            },
        ),
    ]
