# Generated by Django 6.0.2 on 2026-02-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_add_item_change_log"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={"ordering": ["name", "manufacturer"]},
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="manufacturer",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Manufacturer or supplier name (e.g., Briess, Rahr, Viking)",
                max_length=100,
            ),
        ),
    ]
